name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@airdao'
          cache: 'yarn'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: forge install
      - run: yarn symlink
      - run: yarn compile
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
